# Generated by Django 4.1.4 on 2023-01-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu', models.CharField(blank=True, max_length=10, null=True, verbose_name='БЮ')),
                ('store', models.CharField(db_index=True, max_length=20, verbose_name='Склад')),
                ('place', models.CharField(db_index=True, max_length=20, verbose_name='Местоположение')),
                ('code', models.CharField(db_index=True, max_length=12, verbose_name='Код номенклатуры')),
                ('short_name', models.CharField(max_length=50, verbose_name='Краткое наименование')),
                ('name', models.CharField(max_length=200, verbose_name='Описание товара')),
                ('reason_code', models.CharField(default='', max_length=30, verbose_name='Reason code')),
                ('tn', models.CharField(max_length=10, verbose_name='ТГ')),
                ('ng', models.CharField(max_length=10, verbose_name='НГ')),
                ('physical_num', models.IntegerField(db_index=True, default=0, verbose_name='Физические запасы')),
                ('reserve_num', models.IntegerField(default=0, verbose_name='Зарезервировано')),
                ('sale_num', models.IntegerField(default=0, verbose_name='Продано')),
                ('dost_num', models.IntegerField(default=0, verbose_name='Передано на доставку')),
                ('free_num', models.IntegerField(db_index=True, default=0, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('code',),
                'index_together': {('store', 'place', 'code', 'physical_num', 'free_num')},
            },
        ),
    ]
