# Generated by Django 4.1.4 on 2023-01-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tn',
            new_name='tg',
        ),
    ]
