# Generated by Django 4.1.4 on 2023-01-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default='2023-01-01 00:00:00', verbose_name='время записи'),
        ),
    ]
