# Generated by Django 4.1.4 on 2023-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='inventory',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='counted_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Посчитано'),
        ),
        migrations.AlterIndexTogether(
            name='inventory',
            index_together={('store', 'place', 'code', 'physical_num', 'free_num', 'counted_num')},
        ),
    ]
