# Generated by Django 4.1.4 on 2023-01-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_index_together_inventory_counted_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ng',
        ),
    ]
