# Generated by Django 4.1.4 on 2023-01-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_ng'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='delta_num',
            field=models.IntegerField(default=0, verbose_name='Дельта'),
        ),
    ]
