# Generated by Django 4.1.4 on 2023-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_delta_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(db_index=True, max_length=20, verbose_name='Местоположение')),
                ('code', models.CharField(db_index=True, max_length=12, verbose_name='Код номенклатуры')),
                ('num', models.IntegerField(db_index=True, default=0, verbose_name='Физические запасы')),
            ],
            options={
                'verbose_name': 'Посчитанный товар',
                'verbose_name_plural': 'Посчитанный товары',
                'ordering': ('code',),
                'index_together': {('place', 'code', 'num')},
            },
        ),
    ]
