# Generated by Django 4.1.4 on 2023-01-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_checkcell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckCell',
        ),
    ]
