# Generated by Django 4.1.4 on 2023-01-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Бизнес юнит')),
            ],
            options={
                'verbose_name': 'Бизнес юнит',
                'verbose_name_plural': 'Бизнес юниты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=20, verbose_name='Склад')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.bu', verbose_name='БЮ')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ('storage',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True, verbose_name='Код номенклатуры')),
                ('place', models.CharField(max_length=50, verbose_name='Местоположение')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('name', models.CharField(max_length=300, verbose_name='Описание товара')),
                ('reason_code', models.CharField(max_length=100, verbose_name='Reason code')),
                ('tn', models.CharField(max_length=100, verbose_name='ТН')),
                ('ng', models.CharField(max_length=100, verbose_name='НГ')),
                ('provider', models.CharField(max_length=300, verbose_name='Поставщик')),
                ('provider_name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('physical_stocks', models.CharField(blank=True, max_length=5, verbose_name='Физические запасы')),
                ('delivery', models.CharField(blank=True, max_length=5, verbose_name='Передано на доставку')),
                ('sales', models.CharField(blank=True, max_length=5, verbose_name='Продано')),
                ('reserved', models.CharField(blank=True, max_length=5, verbose_name='Зарезервировано')),
                ('available', models.CharField(blank=True, max_length=5, verbose_name='Доступно')),
                ('doc_number', models.CharField(blank=True, max_length=250, verbose_name='Номер документа')),
                ('client_number', models.CharField(blank=True, max_length=250, verbose_name='Счет клиента')),
                ('client', models.CharField(blank=True, max_length=250, verbose_name='Клиент')),
                ('week', models.CharField(blank=True, max_length=50, verbose_name='Неделя')),
                ('delivery_type', models.CharField(blank=True, max_length=5, verbose_name='Тип доставки')),
                ('bu', models.ForeignKey(default='825', on_delete=django.db.models.deletion.CASCADE, to='place.bu', verbose_name='БЮ')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('code',),
                'index_together': {('id', 'code', 'storage')},
            },
        ),
    ]
